spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - StripPrefix=2
            - name: LoggingOrderFilter
            - name: Authentication
              args:
                enabled: true

        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/v1/inventory/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=X-Custom-Header,Ashish

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  securityKey: hsdhfsfkljshdfjkhsfhwioepiuoweipoweipoewpphjiwehjiwpeiohuiowehoiwenjsdfhli