spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 1000
        max-interval: 2000
        max-attempts: 100

# For debugging Config Server issues
logging:
  level:
    org.springframework.cloud.config: DEBUG
    org.springframework.boot.autoconfigure.condition: DEBUG