spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ${spring.application.name}
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json :
          trusted.packages : com.microservice.*

  datasource:
    username: postgres
    password: manager
    url: jdbc:postgresql://localhost:5432/dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true


server:
  port: 7061

kafka:
  topic:
    random-topic: user-random-topic
    user-created: user-created