spring:
  application:
    name: user-service
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://localhost:8081

  datasource:
    url: jdbc:postgresql://localhost:5432/dev
    username: postgres
    password: manager
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

server:
  port: 7062

kafka:
  topic:
    random-topic: user-random-topic
    user-created: user-created
