spring:
  application:
    name: user-service
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  datasource:
    username: postgres
    password: manager
    url: jdbc:postgresql://localhost:5432/dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true


server:
  port: 7062


kafka:
  topic:
    random-topic: user-random-topic
    user-created: user-created