-- data.sql
INSERT INTO products (title, price, stock) VALUES ('Laptop', 999.99, 50);
INSERT INTO products (title, price, stock) VALUES ('Smartphone', 499.99, 120);
INSERT INTO products (title, price, stock) VALUES ('Headphones', 79.99, 200);
INSERT INTO products (title, price, stock) VALUES ('Tablet', 299.99, 75);
INSERT INTO products (title, price, stock) VALUES ('Smartwatch', 199.99, 150);
INSERT INTO products (title, price, stock) VALUES ('Bluetooth Speaker', 129.99, 80);
INSERT INTO products (title, price, stock) VALUES ('Gaming Monitor', 349.99, 30);
INSERT INTO products (title, price, stock) VALUES ('Wireless Mouse', 39.99, 300);
INSERT INTO products (title, price, stock) VALUES ('Mechanical Keyboard', 89.99, 150);
INSERT INTO products (title, price, stock) VALUES ('Digital Camera', 599.99, 40);
INSERT INTO products (title, price, stock) VALUES ('External Hard Drive', 99.99, 200);
INSERT INTO products (title, price, stock) VALUES ('USB Flash Drive', 19.99, 500);
INSERT INTO products (title, price, stock) VALUES ('E-reader', 149.99, 60);
INSERT INTO products (title, price, stock) VALUES ('Action Camera', 249.99, 35);
INSERT INTO products (title, price, stock) VALUES ('Drone', 799.99, 20);
INSERT INTO products (title, price, stock) VALUES ('VR Headset', 299.99, 15);
INSERT INTO products (title, price, stock) VALUES ('Portable Charger', 29.99, 400);
INSERT INTO products (title, price, stock) VALUES ('Streaming Device', 49.99, 250);
INSERT INTO products (title, price, stock) VALUES ('Laptop Stand', 39.99, 150);
INSERT INTO products (title, price, stock) VALUES ('Ergonomic Chair', 199.99, 25);
INSERT INTO products (title, price, stock) VALUES ('Desk Organizer', 19.99, 300);
INSERT INTO products (title, price, stock) VALUES ('Gaming Chair', 249.99, 10);
INSERT INTO products (title, price, stock) VALUES ('LED Desk Lamp', 59.99, 200);
INSERT INTO products (title, price, stock) VALUES ('Webcam', 79.99, 100);
INSERT INTO products (title, price, stock) VALUES ('Microphone', 129.99, 80);
INSERT INTO products (title, price, stock) VALUES ('Graphics Card', 499.99, 15);
INSERT INTO products (title, price, stock) VALUES ('Motherboard', 149.99, 30);
INSERT INTO products (title, price, stock) VALUES ('RAM Module', 89.99, 60);
INSERT INTO products (title, price, stock) VALUES ('Power Supply', 79.99, 50);
INSERT INTO products (title, price, stock) VALUES ('PC Case', 69.99, 40);
INSERT INTO products (title, price, stock) VALUES ('CPU Cooler', 59.99, 55);
INSERT INTO products (title, price, stock) VALUES ('SSD', 129.99, 70);
INSERT INTO products (title, price, stock) VALUES ('HDD', 69.99, 80);
INSERT INTO products (title, price, stock) VALUES ('Network Router', 99.99, 45);
INSERT INTO products (title, price, stock) VALUES ('Home Security Camera', 149.99, 25);
